package com.project.hr.servlets;
import com.project.hr.dl.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;

public class EditHospital extends HttpServlet
{
public void doGet(HttpServletRequest request,HttpServletResponse response)
{
int hospitalNumber=0;
try
{
hospitalNumber=Integer.parseInt(request.getParameter("hospitalNumber"));
}catch(NumberFormatException nfe)
{
// send back view
return;
}
HospitalDAO hospitalDAO=new HospitalDAO();
try
{
HospitalDTO hospital=hospitalDAO.getByHospitalNumber(hospitalNumber);
PrintWriter pw=response.getWriter();
response.setContentType("text/html");
pw.println("<!DOCTYPE html>");
pw.println("<html>");
pw.println("");
pw.println("<head>");
pw.println("    <title>Add Hospital</title>");
pw.println("    <meta name='viewport' content='width=device-width, initial-scale=1'>");
pw.println("    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>");
pw.println("");
pw.println("    <script>");
pw.println("        function validateForm(frm) {");
pw.println("            var firstInvalidComponent = null;");
pw.println("            var valid = true;");
pw.println("");
pw.println("            var hospitalName = frm.hospitalName.value.trim();");
pw.println("            var hospitalNameErrorSection = document.getElementById('hospitalNameErrorSection');");
pw.println("            hospitalNameErrorSection.innerHTML = '';");
pw.println("            if (hospitalName.length == 0) {");
pw.println("                hospitalNameErrorSection.innerHTML = 'Hospital Name Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.hospitalName;");
pw.println("            }");
pw.println("");
pw.println("            var hospitalContact = frm.hospitalContact.value.trim();");
pw.println("            var hospitalContactErrorSection = document.getElementById('hospitalContactErrorSection');");
pw.println("            hospitalContactErrorSection.innerHTML = '';");
pw.println("            if (hospitalContact.length == 0) {");
pw.println("                hospitalContactErrorSection.innerHTML = 'Hospital Contact Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.hospitalContact;");
pw.println("            }");
pw.println("            if (hospitalContact.length != 10) {");
pw.println("                hospitalContactErrorSection.innerHTML = 'Contact should be of 10 digits only';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.hospitalContact;");
pw.println("            }");
pw.println("");
pw.println("");
pw.println("            var totalBeds = frm.totalBeds.value.trim();");
pw.println("            var totalBedsErrorSection = document.getElementById('totalBedsErrorSection');");
pw.println("            totalBedsErrorSection.innerHTML = '';");
pw.println("            if (totalBeds.length == 0) {");
pw.println("                totalBedsErrorSection.innerHTML = 'Total Beds Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.totalBeds;");
pw.println("            }");
pw.println("");
pw.println("            var bedsAvailable = frm.bedsAvailable.value.trim();");
pw.println("            var bedsAvailableErrorSection = document.getElementById('bedsAvailableErrorSection');");
pw.println("            bedsAvailableErrorSection.innerHTML = '';");
pw.println("            if (bedsAvailable.length == 0) {");
pw.println("                bedsAvailableErrorSection.innerHTML = 'Beds Available Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.bedsAvailable;");
pw.println("            }");
pw.println("            if (bedsAvailable.length > totalBeds.length) {");
pw.println("                bedsAvailableErrorSection.innerHTML = 'Availability is more than total beds';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.bedsAvailable;");
pw.println("            }");
pw.println("");
pw.println("            var totalVentilators = frm.totalVentilators.value.trim();");
pw.println("            var totalVentilatorsErrorSection = document.getElementById('totalVentilatorsErrorSection');");
pw.println("            totalVentilatorsErrorSection.innerHTML = '';");
pw.println("            if (totalVentilators.length == 0) {");
pw.println("                totalVentilatorsErrorSection.innerHTML = 'Total Ventilators Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.totalVentilators;");
pw.println("            }");
pw.println("");
pw.println("            var ventilatorsAvailable = frm.ventilatorsAvailable.value.trim();");
pw.println("            var ventilatorsAvailableErrorSection = document.getElementById('ventilatorsAvailableErrorSection');");
pw.println("            ventilatorsAvailableErrorSection.innerHTML = '';");
pw.println("            if (ventilatorsAvailable.length == 0) {");
pw.println("                ventilatorsAvailableErrorSection.innerHTML = 'Ventilators Available Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.ventilatorsAvailable;");
pw.println("            }");
pw.println("            if (ventilatorsAvailable.length > totalVentilators.length) {");
pw.println("                ventilatorsAvailableErrorSection.innerHTML = 'Availability is more than total ventilators';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.ventilatorsAvailable;");
pw.println("            }");
pw.println("var totalICU = frm.totalICU.value.trim();");
pw.println("            var totalICUErrorSection = document.getElementById('totalICUErrorSection');");
pw.println("            totalICUErrorSection.innerHTML = '';");
pw.println("            if (totalICU.length == 0) {");
pw.println("                totalICUErrorSection.innerHTML = 'Total ICU Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.totalICU;");
pw.println("            }");
pw.println("            5");
pw.println("            var icuAvailable = frm.icuAvailable.value.trim();");
pw.println("            var icuAvailableErrorSection = document.getElementById('icuAvailableErrorSection');");
pw.println("            icuAvailableErrorSection.innerHTML = '';");
pw.println("            if (icuAvailable.length == 0) {");
pw.println("                icuAvailableErrorSection.innerHTML = 'ICU Available Required';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.icuAvailable;");
pw.println("            }");
pw.println("            if (icuAvailable.length > totalICU.length) {");
pw.println("                icuAvailableErrorSection.innerHTML = 'Availability is more than total ICUs';");
pw.println("                valid = false;");
pw.println("                firstInvalidComponent = frm.icuAvailable;");
pw.println("            }");
pw.println("            if (!valid) firstInvalidComponent.focus();");
pw.println("            return valid;");
pw.println("        }");
pw.println("");
pw.println("        function cancelEditing() {");
pw.println("            document.getElementById('cancelEditingForm').submit();");
pw.println("        }");
pw.println("    </script>");
pw.println("    <style>");
pw.println("        .upper {");
pw.println("            margin-top: -35px;");
pw.println("            margin-left: 15vh;");
pw.println("            font-size: 25px;");
pw.println("            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;");
pw.println("        }");
pw.println("        ");
pw.println("        .ujjain {");
pw.println("            color: rgb(134, 134, 131);");
pw.println("            font-size: 25px;");
pw.println("            margin-left: 130px;");
pw.println("            margin-top: -40px;");
pw.println("            font-family: 'Times New Roman', Times, serif;");
pw.println("            position: -webkit-sticky;");
pw.println("            position: sticky;");
pw.println("            overflow: hidden;");
pw.println("            font-size: 25px;");
pw.println("        }");
pw.println("        ");
pw.println("        .header {");
pw.println("            height: 45px;");
pw.println("            width: 45px;");
pw.println("            margin-top: 50px;");
pw.println("            margin-left: 90px;");
pw.println("            position: -webkit-sticky;");
pw.println("            position: sticky;");
pw.println("            overflow: hidden;");
pw.println("        }");
pw.println("        ");
pw.println("        ul {");
pw.println("            list-style-type: none;");
pw.println("            margin-left: 70vh;");
pw.println("            padding: 0;");
pw.println("            overflow: hidden;");
pw.println("            position: -webkit-sticky;");
pw.println("            position: sticky;");
pw.println("            top: 0;");
pw.println("        }");
pw.println("        ");
pw.println("        li {");
pw.println("            float: left;");
pw.println("        }");
pw.println("        ");
pw.println("        li a {");
pw.println("            font-size: 19px;");
pw.println("            background-color: rgb(112, 190, 201);");
pw.println("            display: block;");
pw.println("            color: rgb(7, 7, 7);");
pw.println("            ;");
pw.println("            text-align: center;");
pw.println("            padding: 14px 16px;");
pw.println("            text-decoration: none;");
pw.println("        }");
pw.println("        ");
pw.println("        li a:hover {");
pw.println("            background-color: rgb(70, 155, 141);");
pw.println("        }");
pw.println("        ");
pw.println("        .mail:hover {");
pw.println("            color: lawngreen;");
pw.println("        }");
pw.println("        ");
pw.println("        .background {");
pw.println("            background-color: #000000;");
pw.println("        }");
pw.println("        ");
pw.println("        .form {");
pw.println("            color: rgba(10, 7, 7, 0.953);");
pw.println("            font-size: 20px;");
pw.println("        }");
pw.println("    </style>");
pw.println("");
pw.println("</head>");
pw.println("");
pw.println("<body>");
pw.println("    <div>");
pw.println("");
pw.println("        <img src='images/logo.png' style='height: 30x; width: 30px; margin-left:80px ; position: static;'>");
pw.println("        <u><p class='upper'>ospital Update At Your Hands</p></u>");
pw.println("    </div>");
pw.println("    <hr style='margin-top: -10px;'>");
pw.println("    <div style='text-align: right;margin-top: -45px '>");
pw.println("        <span class='phone-icon' style='padding-right: 20px;'><i class='fa fa-phone' style='color: lawngreen;'></i> 9174057563</span>");
pw.println("");
pw.println("        <span class='date-icon' style='padding-right: 20px;'><i class='fa fa-calendar-plus-o'  style='color: lawngreen;'></i> 6:00 AM - 10:00 PM (Mon-Fri)</span>");
pw.println("        <span class='email-icon' style='padding-right: 20px;'><i class='fa fa-envelope-o'  style='color: lawngreen;'></i> <a href='#' class='mail' style='text-decoration: none;color: black;'  >rajeevanjana143@gmail.com</a></span>");
pw.println("    </div>");
pw.println("    <div style='margin-top: -30px;'>");
pw.println("<img src='images/A-logo.png ' class='header '>");
pw.println("        <u><b><i> <p class='ujjain' style='background-color: rgba(15, 15, 15, 0.986); width: 160px;'>ll About Ujjain</p></i></b></u>");
pw.println("    </div>");
pw.println("    <img src='images/about-bg.jpg' height='696px' width='1530px' style='margin-top: -65px; margin-left: -10px;'>");
pw.println("    <div style='margin-top: -710px; ; '>");
pw.println("");
pw.println("        <i><b><ul>");
pw.println("");
pw.println("");
pw.println("    <li><a href='/minor/index.html#top' class='smoothScroll'>Home</a></li>");
pw.println("                    <li><a href='/minor/index.html#about' class='smoothScroll'>About Us</a></li>");
pw.println("                    <li>");
pw.println("                        <a href='/minor/hospitalsView' class='smoothScroll'>Hospitals</a>");
pw.println("                    </li>");
pw.println("                    <li>");
pw.println("                        <a href='/minor/patientsView' class='smoothscroll'>Patients</a>");
pw.println("                    </li>");
pw.println("                    <li><a href='/minor/index.html#contactUs' class='smoothScroll'>Contact Us</a></li>");
pw.println("                    <li>");
pw.println("                        <a href='https://selfregistration.cowin.gov.in/'>Book Vaccine</a>");
pw.println("                    </li>");
pw.println("");
pw.println("            <li><a href='/minor/index.html#enquiry '>Make an Enquiry</a></li>");
pw.println("");
pw.println("");
pw.println("");
pw.println("");
pw.println("");
pw.println("");
pw.println("");
pw.println("        </ul></b></i>");
pw.println("    </div>");
pw.println("    <div style='height:65vh; margin-left:105px; margin-right:5px; margin-bottom:px; margin-top:85px; padding:5px; border:1px solid black'>");
pw.println("<h1>Hospital (Edit Module)</h1>");
pw.println("<form method='post' action='/minor/updateHospital' onsubmit='return validateForm(this)'>");
pw.println("<input type='hidden' name='hospitalNumber' id='hospitalNumber' value='"+hospitalNumber+"'");
pw.println("<table>");
pw.println("<tr>");
pw.println("<td>Hospital Name</td>");
pw.println("<td>");
String hospitalName=hospital.getHospitalName();
pw.println("<input type='text' id='hospitalName' name='hospitalName' maxlength='100' size='36'<br>");
pw.println("<span id='hospitalNameErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>Total Beds</td>");
pw.println("<td>");
int totalBeds=hospital.getTotalBeds();
pw.println("<input type='number' id='totalBeds' name='totalBeds' maxLength='2' size='36'<br>");
pw.println("<span id='totalBedsErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>Beds Available</td>");
pw.println("<td>");
int bedsAvailable=hospital.getBedsAvailable();
pw.println("<input type='number' id='bedsAvailable' name='bedsAvailable' maxLength='2' size='36'<br>");
pw.println("<span id='bedsAvailableErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>Total Ventilators</td>");
pw.println("<td>");
int totalVentilators=hospital.getTotalVentilators();
pw.println("<input type='number' id='totalVentilators' name='totalVentilators' maxLength='2' size='36'<br>");
pw.println("<span id='totalVentilatorsErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>Ventilators Available</td>");
pw.println("<td>");
int ventilatorsAvailable=hospital.getVentilatorsAvailable();
pw.println("<input type='number' id='ventilatorsAvailable' name='ventilatorsAvailable' maxLength='2' size='36'<br>");
pw.println("<span id='ventilatorsAvailableErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>Total ICUs</td>");
pw.println("<td>");
int totalICU=hospital.getTotalICU();
pw.println("<input type='number' id='totalICU' name='totalICU' maxLength='2' size='36'<br>");
pw.println("<span id='totalICUErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>ICUs Available</td>");
pw.println("<td>");
int icuAvailable=hospital.getICUAvailable();
pw.println("<input type='number' id='icuAvailable' name='icuAvailable' maxLength='2' size='36'<br>");
pw.println("<span id='icuAvailableErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("<tr>");
pw.println("<td>Hospital Contact</td>");
pw.println("<td>");
String hospitalContact=hospital.getHospitalContact();
pw.println("<input type='text' id='hospitalContact' name='hospitalContact' maxlength='10' size='36'<br>");
pw.println("<span id='hospitalContactErrorSection' style='color: red'></span></td>");
pw.println("</tr>");
pw.println("                <td colspan='2'><button type='submit' style='padding:5px;margin-top: 20px;margin-left: 60px; background-color: lawngreen;'>Edit</button> &nbsp;&nbsp;&nbsp;&nbsp;");
pw.println("<button type='button' onclick='cancelEditing()' style='padding: 5px;background-color: lawngreen;'>Cancel</button></td>");
pw.println("            </table>");
pw.println("        </form>");
pw.println("    </div>");
pw.println("");
pw.println("</body>");
pw.println("");
pw.println("</html>");
}catch(IOException ioException)
{
System.out.println(ioException.getMessage());
}catch(Exception e)
{
System.out.println(e);
}
}
public void doPost(HttpServletRequest request,HttpServletResponse response)
{
doGet(request,response);
}
private void sendBackView(HttpServletResponse response)
{
// send back view page
}
} // class employees view
